package chat;


/**
* chat/ChatClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 10 mars 2017 14 h 31 CET
*/

public interface ChatClient extends ChatClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatClient
