package chat;


/**
* chat/ChatClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 10 mars 2017 10 h 05 CET
*/

public abstract class ChatClientPOA extends org.omg.PortableServer.Servant
 implements chat.ChatClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id", new java.lang.Integer (0));
    _methods.put ("_set_id", new java.lang.Integer (1));
    _methods.put ("_get_nom", new java.lang.Integer (2));
    _methods.put ("_set_nom", new java.lang.Integer (3));
    _methods.put ("sendMessage", new java.lang.Integer (4));
    _methods.put ("setMessage", new java.lang.Integer (5));
    _methods.put ("setListCo", new java.lang.Integer (6));
    _methods.put ("getId", new java.lang.Integer (7));
    _methods.put ("getName", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/ChatClient/_get_id
       {
         int $result = (int)0;
         $result = this.id ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // chat/ChatClient/_set_id
       {
         int newId = in.read_long ();
         this.id (newId);
         out = $rh.createReply();
         break;
       }

       case 2:  // chat/ChatClient/_get_nom
       {
         String $result = null;
         $result = this.nom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // chat/ChatClient/_set_nom
       {
         String newNom = in.read_string ();
         this.nom (newNom);
         out = $rh.createReply();
         break;
       }

       case 4:  // chat/ChatClient/sendMessage
       {
         chat.ChatClient client = chat.ChatClientHelper.read (in);
         String msg = in.read_string ();
         this.sendMessage (client, msg);
         out = $rh.createReply();
         break;
       }

       case 5:  // chat/ChatClient/setMessage
       {
         String nom = in.read_string ();
         String msg = in.read_string ();
         this.setMessage (nom, msg);
         out = $rh.createReply();
         break;
       }

       case 6:  // chat/ChatClient/setListCo
       {
         chat.ChatClient clients[] = chat.ChatClientPackage.ClientsHelper.read (in);
         this.setListCo (clients);
         out = $rh.createReply();
         break;
       }

       case 7:  // chat/ChatClient/getId
       {
         int $result = (int)0;
         $result = this.getId ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // chat/ChatClient/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/ChatClient:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatClient _this() 
  {
    return ChatClientHelper.narrow(
    super._this_object());
  }

  public ChatClient _this(org.omg.CORBA.ORB orb) 
  {
    return ChatClientHelper.narrow(
    super._this_object(orb));
  }


} // class ChatClientPOA
