package chat;


/**
* chat/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 10 mars 2017 14 h 31 CET
*/

public interface ChatServerOperations 
{
  void register (chat.ChatClient c);
  void sendToAll (chat.ChatClient from, String msg);
  void supprimerClient (chat.ChatClient client);
} // interface ChatServerOperations
