package chat.ChatClientPackage;


/**
* chat/ChatClientPackage/ClientsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 10 mars 2017 13 h 19 CET
*/

public final class ClientsHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.ChatClient value[] = null;

  public ClientsHolder ()
  {
  }

  public ClientsHolder (chat.ChatClient[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ChatClientPackage.ClientsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ChatClientPackage.ClientsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ChatClientPackage.ClientsHelper.type ();
  }

}
