package chat.ChatServerPackage;


/**
* chat/ChatServerPackage/clientsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* vendredi 10 mars 2017 14 h 31 CET
*/

public final class clientsHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.ChatClient value[] = null;

  public clientsHolder ()
  {
  }

  public clientsHolder (chat.ChatClient[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ChatServerPackage.clientsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ChatServerPackage.clientsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ChatServerPackage.clientsHelper.type ();
  }

}
